### ISSUE TITLE
Make page mockups for major site features

### ISSUE THREAD

**Issue by tiffz** [LikeMyBread/Saylua#37]
I want to make some quick page mockups for different features on Saylua. No functionality. Just throw together some HTML and CSS and maybe light JavaScript. 

- [x]  Newspaper
- [ ]  Item Database
- [ ]  Inventory
- [ ]  Overworld/Villages
- [ ]  Your house/farm
- [ ]  NPC Shops/User shops
- [ ]  Arcade main page
- [ ]  Wardrobe
- [ ]  Bank
- [ ]  Quest Journal
- [ ]  Pet Dens
- [x]  Pet Rooms/Profiles

**Comment by NoiSek** [comment]
No more pet dens? Or is that included in 'house/farm'?

**Comment by shadowfiles** [comment]
I left out the pet stuff for Mike to do for now haha.

**Comment by tiffz** [comment]
Wish Github differentiated better between closed and complete vs closed and won't do. I think I want to close this issue because I'd rather move in a more agile direction or whatever with doing complete features at a time rather than small parts of every feature.
