### ISSUE TITLE
Better server-side Entity / Tile organization

### ISSUE THREAD

**Issue by NoiSek** [LikeMyBread/Saylua#40]
Entities need to be more than JSON files.

Find some way to write tile / entity schema as Python classes and serialize them into JSON objects for dungeons.

**Comment by shadowfiles** [comment]
You called for help? :O

**Comment by NoiSek** [comment]
cry of desperation, my body is ready for sqlalchemy

**Comment by NoiSek** [comment]
Tide comes in, tide never comes out. You can't explain that.

One way serialization functional as of 22660451c50228b42f32b977c9d24a8b93a7a07c, thanks to SQLAlchemy.

I'm willing to call this done for now, as I see the immediate usefulness of being able to edit entities / tiles and save them as being very low at this stage in development.
